### PR TITLE
fix(ci): update Node versions checked by CI

### PR DESCRIPTION
**Pull request by demurgos**
This commit fixes failing CI and updates the list of checked Node versions to included the latest LTS releases. The CI was failing because AppVeyor is always installing the latest version of `npm`, even on incompatible Node versions. I removed those versions from AppVeyor (they are still checked with Travis).

/cc @bcoe @isaacs @profnandaa

### CODE REVIEW

**Comment by demurgos** [comment]
It turns out that CI is not only failing on Node 5 but also Node `0.12`. I'd keep the lib untouched but drop older Node versions from CI. Could anybody look at it?

/cc @bcoe @isaacs @profnandaa

**Comment by Gudahtt** [comment]
The AppVeyor build is using the latest version of `npm` because it's explicitly being asked to a few lines down:

```
- npm -g install npm@latest
```

You could fix this by removing that line. If you still want to install the latest version of `npm` on more recent Node.js versions, you can conditionally do so. Perhaps something like this:

```
- if "%nodejs_version%" gtr 4 npm -g install npm@latest
```

**Comment by demurgos** [comment]
Thanks, I haven't noticed. I'll simply remove the line installing the latest npm on AppVeyor and check the results.

**Comment by demurgos** [comment]
Closing in favor of #53

**Pull request closed without merging**
